apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: immich-machine-learning
  ports:
    - name: http
      port: 3003
      targetPort: http
