apiVersion: v1
kind: Service
metadata:
  name: immich-valkey
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: immich-valkey
  ports:
    - name: redis
      port: 6379
      targetPort: redis
